base: &base
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: root

development:
  database: client_db
  <<: *base

test:
  database: client_db
  <<: *base

staging:
  database: client_db
  <<: *base

production:
  adapter:  mysql2
  database: code_test_production
  encoding: utf8
  pool:     5
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
